### ISSUE TITLE
Possible bug in HCMV_GenotypeCount.pl

### ISSUE THREAD

**Issue by JasperGeh** [centre-for-virus-research/VATK#2]
When setting the genotype-threshold from their defaults to >25 Reads & >5% total reads (as in Suarez et al. 2019), I got the same number of strains in samples, which should show lower strain count with the stronger filter. I figured that this might be due to an error in line 48, where `if ($perc_genotype>2){$genotype_cnt{$gene}++;}` is executed instead of `($perc_genotype>$perc)`, as specified in line 11.
Am I seeing this wrong or misunderstanding the script? In any case: Very helpful tool! 👍

**Comment by josephhughes** [comment]
Thanks for the feedback, you were right and it is now fixed.
